# Generated by Django 3.2.19 on 2023-06-12 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_reviewcomments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewcomments',
            old_name='comment',
            new_name='comments',
        ),
    ]
