# Generated by Django 3.2.19 on 2023-06-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_comment_reviewcomments_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewcomments',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
