# Generated by Django 3.2.19 on 2023-06-13 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_reviewcomments_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewcomments',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='website.reviews'),
        ),
    ]
